all:
  children:
    routers
    testhosts

routers:
  hosts:
    inetRouter:
      ansible_host: 127.0.0.1 
      ansible_port: 2222
      ansible_ssh_private_key_file: ./.vagrant/machines/inetRouter/virtualbox/private_key

    centralRouter:
      ansible_host: 127.0.0.1 
      ansible_port: 2200
      ansible_ssh_private_key_file: ./.vagrant/machines/centralRouter/virtualbox/private_key

testhosts:
  hosts:
    testServer1:
      ansible_host: 127.0.0.1
      ansible_port: 2201
      ansible_ssh_private_key_file: ./.vagrant/machines/testServer1/virtualbox/private_key

    testClient1:
      ansible_host: 127.0.0.1
      ansible_port: 2203
      ansible_ssh_private_key_file: ./.vagrant/machines/testClient1/virtualbox/private_key

    testServer2:
      ansible_host: 127.0.0.1
      ansible_port: 2202
      ansible_ssh_private_key_file: ./.vagrant/machines/testServer2/virtualbox/private_key

    testClient2:
      ansible_host: 127.0.0.1
      ansible_port: 2204
      ansible_ssh_private_key_file: ./.vagrant/machines/testClient2/virtualbox/private_key