---
 - name: 'Prepare stands LACP and VLANs'
   hosts: all
   become: true
   gather_facts: true
   vars:

   tasks:
     - name: 'Install required packages'
       yum:
         name:
           - nano
           - net-tools
           - tcpdump
         state: present

 - name: 'Enable LACP on inetRouter'
   hosts: inetRouter
   become: true
   vars:
     ipaddr: 192.168.255.1

   tasks:
     - name: 'Copy bond config to host and script for enable NAT'
       template: src={{ item.src }} dest={{ item.dest }}
       with_items:
         - { src: '../templates/inet_router_ifcfg-bond0.j2', dest: '/etc/sysconfig/network-scripts/ifcfg-bond0'}
         - { src: '../templates/ifcfg-eth1.j2', dest: '/etc/sysconfig/network-scripts/ifcfg-eth1'}
         - { src: '../templates/ifcfg-eth2.j2', dest: '/etc/sysconfig/network-scripts/ifcfg-eth2'}
         - { src: '../templates/Enable_NAT.sh', dest: '/root/Enable_NAT.sh'}

     - name: 'Start Firewalld'
       systemd:
         name: firewalld
         state: restarted
         enabled: yes

     - name: 'Enable NAT'
       shell: sh /root/Enable_NAT.sh


 - name: 'Enable LACP on centralRouter'
   hosts: centralRouter
   become: true
   vars:
     ipaddr: 192.168.255.2
     gateway: 192.168.255.1

   tasks:
     - name: 'revmove default gw from vagrant interface'
       blockinfile:
         path: /etc/sysconfig/network-scripts/ifcfg-eth0
         block: |
            DEVICE="eth0"
            BOOTPROTO="dhcp"
            ONBOOT="yes"
            TYPE="Ethernet"
            PERSISTENT_DHCLIENT="yes"
            DEFROUTE=no

     - name: 'Copy bond config to host'
       template: src={{ item.src }} dest={{ item.dest }}
       with_items:
         - { src: '../templates/central_router_ifcfg-bond0.j2', dest: '/etc/sysconfig/network-scripts/ifcfg-bond0'}
         - { src: '../templates/ifcfg-eth1.j2', dest: '/etc/sysconfig/network-scripts/ifcfg-eth1'}
         - { src: '../templates/ifcfg-eth2.j2', dest: '/etc/sysconfig/network-scripts/ifcfg-eth2'}

 - name: 'Enable port forwarding on routers'
   hosts: routers
   become: true

   tasks:
     - name: 'Enable port forwarding'
       sysctl:
         name: net.ipv4.ip_forward
         value: '1'
         sysctl_set: yes

     - name: 'Restart network'
       systemd:
         name: network
         state: restarted
         enabled: yes


 - name: 'Setup VLANs on testServer1'
   hosts: testServer1
   become: true
   vars:
     dev: vlan100
     ip_vlan: 10.10.10.1
     vlan_id: 100

   tasks:
     - name: 'Copy VLAN 100 config'
       template:
         src: '../templates/ifcfg-eth1.vlan.j2'
         dest: '/etc/sysconfig/network-scripts/ifcfg-vlan100'

 - name: 'Setup VLANs on testClient1'
   hosts: testClient1
   become: true
   vars:
     dev: vlan100
     vlan_id: 100
     ip_vlan: 10.10.10.254

   tasks:
     - name: 'Copy VLAN 100 config'
       template:
         src: '../templates/ifcfg-eth1.vlan.j2'
         dest: '/etc/sysconfig/network-scripts/ifcfg-vlan100'

 - name: 'Setup VLANs on testServer2'
   hosts: testServer2
   become: true
   vars:
     dev: vlan200
     vlan_id: 200
     ip_vlan: 10.10.10.1

   tasks:
     - name: 'Copy VLAN 200 config'
       template:
         src: '../templates/ifcfg-eth1.vlan.j2'
         dest: '/etc/sysconfig/network-scripts/ifcfg-vlan200'

 - name: 'Setup VLANs on testClient2'
   hosts: testClient2
   become: true
   vars:
     dev: vlan200
     vlan_id: 200
     ip_vlan: 10.10.10.254

   tasks:
     - name: 'Copy VLAN 200 config'
       template:
         src: '../templates/ifcfg-eth1.vlan.j2'
         dest: '/etc/sysconfig/network-scripts/ifcfg-vlan200'

 - name: 'Restart Networks on testhosts'
   hosts: testhosts
   become: true

   tasks:
   - name: 'Restart network'
     systemd:
       name: network
       state: restarted
       enabled: yes







